version: "3.9"

services:
    site:
        container_name: cobsa-website
        image: cobsa-website
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "4099:8080"